version: '3'

networks:
  employee-aggregator:

services:
  employee-php:
    user: 1000:1000
    build:
      context: ./src/employee-api
      dockerfile: ./config/php/Dockerfile
      args:
        env_type: "local"
    container_name: EmployeePhp
    environment:
      PHP_IDE_CONFIG: "serverName=docker_container"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=192.168.1.13"
    expose:
      - 9000
    networks:
      - employee-aggregator
    volumes:
      - ./src/employee-api/src:/var/www/employee_php
      - ./src/employee-api/config/php/php.ini:/usr/local/etc/php/php.ini
      - /var/www/employee_php/vendor

  employee-php-web:
    image: library/nginx:1.20.1
    container_name: EmployeePhpWeb
    volumes:
      - ./src/employee-api/src:/var/www/employee_php
      - ./src/employee-api/config/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8007:80"
    networks:
      - employee-aggregator
    depends_on:
      - employee-php

  employee-admin:
    user: 1000:1000
    build:
      context: ./src/employee-admin
      dockerfile: ./config/web-local/Dockerfile
      args:
        env_type: "local"
    container_name: EmployeeAdmin
    volumes:
      - ./src/employee-admin/src:/usr/src/employee-admin
      - /usr/src/employee-admin/node_modules
    networks:
      - employee-aggregator
    ports:
      - "8081:8081"
