version: '3'

services:
  db:
    image: mysql:8.0
    platform: 'linux/x86_64'
    container_name: test-db
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - 3406:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  test-php:
    build:
      context: .
      dockerfile: config/php/Dockerfile
      args:
        env_type: "local"
    container_name: TestPhp
    environment:
      PHP_IDE_CONFIG: "serverName=docker_container"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=192.168.1.13"
    volumes:
      - ./src:/var/www/test_php
      - ./config/php/php.ini:/usr/local/etc/php/php.ini


  test-php-web:
    image: library/nginx:1.20.1
    container_name: TestPhpWeb
    volumes:
      - ./src:/var/www/test_php
      - ./config/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8006:80"
